// Code generated by DevUp technologies, 02/08/2024 14:39:06
using InventoryManagementBlzUi;
using InventoryManagementBlzUi.APIClient;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");

builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });

string baseUri= "https://localhost:7100/";

builder.Services.AddHttpClient<ProductAPIClient>(options =>
		{
	options.BaseAddress = new Uri(baseUri);
		});



// builder.Services.AddHttpClient<ProductAPIClient>(options =>
// {
    // options.BaseAddress = new Uri("https://localhost:7097/api");
// });

await builder.Build().RunAsync();

