// Code generated by DevUp technologies, 02/08/2024 14:39:06
namespace InventoryManagementBlzUi.Models
{
    public class ProductFilterModel
    {
		public ProductFilterModel()
		{
			CategoryId = null;
			NetPrice = null;
			SalesPrice = null;
			StockQuantity = null;
			Status = null;
			Name = null;
			ProductionDateFrom = null;
			ProductionDateTo = null;

			Ascending = null;
		}
		
		public System.Int64 Id { get; set; }
		public Nullable<System.Int32> CategoryId { get; set; }
		public Nullable<System.Decimal> NetPrice { get; set; }
		public Nullable<System.Decimal> SalesPrice { get; set; }
		public Nullable<System.Double> StockQuantity { get; set; }
		public Nullable<System.Int32> Status { get; set; }
		public System.String? Name { get; set; }
		public Nullable<System.DateTime> ProductionDateFrom { get; set; }
		public Nullable<System.DateTime> ProductionDateTo { get; set; }


        //paging and orderby attributes
        public Nullable<bool> Ascending { get; set; }
        public string? OrderByColumnName { get; set; }
        public Nullable<System.Int32> PageNumber { get; set; }
        public Nullable<System.Int32> PageSize { get; set; }
    }
}

